### PR TITLE
Fix documentation when using SingleInstance

### LINKED ISSUE #118: Error: ConfigurationValidationException on a apply
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
Plan goes ok.
After trying to apply my config, a **ConfigurationValidationException** pops up

## Expected Behavior
Clearer meaning of the problem. I think I used all the required vars documented... so no clue how to proceed

## Steps to Reproduce
`
module "elastic_beanstalk_application" {
  source      = "git::https://github.com/cloudposse/terraform-aws-elastic-beanstalk-application.git?ref=tags/0.5.0"
  name        = "AppName"
}

module "elastic-beanstalk-environment" {
  source  = "cloudposse/elastic-beanstalk-environment/aws"
  version = "0.22.0"
  elastic_beanstalk_application_name = "AppName"
  name = "dev-AppName"
  vpc_id = aws_default_vpc.default.id
  region = "eu-west-1"
  solution_stack_name = "64bit Amazon Linux 2 v5.0.2 running Node.js 12"
  application_subnets = [
    aws_default_subnet.default_az1.id,
    aws_default_subnet.default_az2.id,
    aws_default_subnet.default_az3.id,
  ]
  autoscale_max = 2
  env_vars = {
    API_URL = "https://my-api-url.net"
  }
}
`

## Screenshots
Captura de Pantalla 2020-06-04 a les 13 15 48
`
Error: ConfigurationValidationException: Configuration validation exception: Invalid option value: '' (Namespace: 'aws:ec2:vpc', OptionName: 'ELBSubnets'): Specify the subnets for the VPC.
	status code: 400, request id: ac1268fc-77a0-479d-8a5d-37c6b024ce9b

  on .terraform/modules/elastic-beanstalk-environment/terraform-aws-elastic-beanstalk-environment-0.22.0/main.tf line 505, in resource "aws_elastic_beanstalk_environment" "default":
 505: resource "aws_elastic_beanstalk_environment" "default" {
`

## Environment:
 - OS: OSX
 - Version Dockerized Terraform v0.12.21

### PR DESCRIPTION
**Pull request by Pijuli**
## what
Update readme

## why
When trying to apply changes (not plan) using SingleInstance I had the following error:

Error: ConfigurationValidationException: Configuration validation exception: Invalid option value: '0.0' (Namespace: 'aws:autoscaling:updatepolicy:rollingupdate', OptionName: 'MinInstancesInService'): You can't enable rolling updates for a single-instance environment.
	status code: 400,

Undocumented on the readme file stating that "rolling_update_enabled " should be set to false if mode is SingleInstance

## references
`closes #118 `

### CODE REVIEW

**Comment by jamengual** [comment]
@Pijuli can you fix the conflicts? you might have to do it from a branch and not master

**Comment by jamengual** [comment]
well it looks like another PR addressed your changes, it shows 0 changes

**Comment by Pijuli** [comment]
I'm dumb. There you go

https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/pull/122

**Pull request closed without merging**
