### PR TITLE
fix always dirty aws_security_group.default

### LINKED ISSUE #148: resource "aws_security_group" "default" is always dirty
I have the following setting
```
allowed_security_groups = []
```
with or without that parameter, I get the output below every time I run `terraform plan`

```
  ~ resource "aws_security_group" "default" {
        arn                    = "arn:aws:ec2:us-east-2:xxxxxxxxxxx:security-group/sg-xxxxxxxxxxxxxx"
        description            = "Allow inbound traffic from provided Security Groups"
        egress                 = [
            {
                cidr_blocks      = [
                    "0.0.0.0/0",
                ]
                description      = ""
                from_port        = 0
                ipv6_cidr_blocks = []
                prefix_list_ids  = []
                protocol         = "-1"
                security_groups  = []
                self             = false
                to_port          = 0
            },
        ]
        id                     = "sg-xxxxxxxxxxxxxx"
      ~ ingress                = [
          + {
              + cidr_blocks      = []
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
        name                   = "beanstalk-development"
        owner_id               = "xxxxxxxxxxxxxx"
        revoke_rules_on_delete = false
        tags                   = {
            "Name" = "beanstalk-development"
        }
        vpc_id                 = "vpc-xxxxxxxxxxxxxxxx"
    }
```

How that can be avoided?

### PR DESCRIPTION
**Pull request by RomanNess**
Fixes #148.

I tested the fix in a project that uses the module. 
Though, I was too lazy to checkout this repo and did the changes in the web editor. I hope that I did not mess up the formatting.

### CODE REVIEW

**Comment by RomanNess** [comment]
@osterman Not sure who else to ping about this. This PR has been laying around for two weeks and I don't know if this is due to the automatic checks not starting for some reason. Is there anything else that you require from my side?

**Comment by florian0410** [comment]
Thank you for your PR @RomanNess 
Just tested the change and it works perfectly even after all this time. I need it too currently. 
Las time I did a PR it was @Gowiem that validated it. I wonder if he could go through this one since it seems to fix the issue in a clean way.
I'll try to ping the slack too just in case.

**Review by joe-niland — APPROVED** [review]

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
Thanks for the contribution @RomanNess! Released as [0.39.1](https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/releases/tag/0.39.1).

**Pull request merged**
