### PR TITLE
Modifications to allow using network ELB type 

### PR DESCRIPTION
**Pull request by xanderv87**
Not sure if this will fix it, can't get the tests to work locally.

But if I can guess the merge command doesn't work nicely with the null input, changed this to [].

### CODE REVIEW

**Comment by jamengual** [comment]
@xanderv87  can you rebase from master please?

**Comment by osterman** [comment]
image

**Comment by osterman** [comment]
Check out the errors here: https://github.com/cloudposse/actions/actions/runs/170351690

**Comment by jamengual** [comment]
@xanderv87 is this still relevant?

**Pull request closed without merging**
