### PR TITLE
Settings changes fix

### LINKED ISSUE #43: Module recreates all `settings` on each `terraform plan/apply`
`terraform-aws-elastic-beanstalk-environment` recreates all `settings` on each `terraform plan/apply`

  ```
      setting.1039973377.name:               "InstancePort" => "InstancePort"
      setting.1039973377.namespace:      "aws:elb:listener:22" => "aws:elb:listener:22"
      setting.1039973377.resource:           "" => ""
      setting.1039973377.value:                "22" => "22"
      setting.1119692372.name:               "" => "ListenerEnabled"
      setting.1119692372.namespace:      "" => "aws:elbv2:listener:443"
      setting.1119692372.resource:           "" => ""
      setting.1119692372.value:                "" => "false"
      setting.1136119684.name:               "RootVolumeSize" => "RootVolumeSize"
      setting.1136119684.namespace:     "aws:autoscaling:launchconfiguration" => "aws:autoscaling:launchconfiguration"
      setting.1136119684.resource:           "" => ""
      setting.1136119684.value:              "8" => "8"
      setting.1201312680.name:             "ListenerEnabled" => "ListenerEnabled"
      setting.1201312680.namespace:   "aws:elb:listener:443" => "aws:elb:listener:443"
      setting.1201312680.resource:         "" => ""
      setting.1201312680.value:             "false" => "false"
```

This feature/bug was present for years and is still not fixed:

https://github.com/hashicorp/terraform/issues/6729
https://github.com/terraform-providers/terraform-provider-aws/pull/901
https://github.com/hashicorp/terraform/issues/6257
https://github.com/terraform-providers/terraform-provider-aws/issues/280
https://github.com/hashicorp/terraform/issues/11056
https://github.com/terraform-providers/terraform-provider-aws/issues/461

(tested some ideas from the links above, nothing worked 100%)

The only possible solution is to add this:

```
lifecycle {
    ignore_changes = ["setting"]
}
```

but it’s a hack since it will not update the env if you update any of the settings.

Regarding `terraform-aws-elastic-beanstalk-environment` recreating the `settings` all the time, here what’s probably happening:

- Terraform sends all settings to AWS, but some of them are not relevant to the environment you are deploying
- Elastic Beanstalk accepts all settings, applies the relevant ones, and throws away the rest
- Next time Terraform asks about the settings, Elastic Beanstalk returns a subset of the values and probably in different order
- Terraform can’t decide/calculate if the settings are the same - they sure look different (and would require an `advanced` algorithm to determine if they are the same)
- Terraform assigns new ID to the entire array of settings and tries to recreate all of them
- Elastic Beanstalk accepts the settings, applies the relevant ones, and throws away the rest - the cycle repeats

What’s a possible solution?
Introduce `var.settings` (list of maps) to be able to provide all the required settings from outside of the module.
It might work, but in practice would be very difficult to know all the needed settings and tedious to implement.

### PR DESCRIPTION
**Pull request by helvalius**
## what
* Fix of #43 for terraform 0.12.x for now and separated classic & application ELB settings 

## why
* As #43 shows, terraform 0.12.x shows settings changes during ```terraform plan```when no changes were done.
* furthermore, if you are using an application load balancer the classic ELB settings are always shown as changes. I used the AWS documentation of "deprecated" classic ELB values if you are using an ALB to decide which settings go into which of the two lists. 

## references
* closes #43 for terraform 0.12.x

### CODE REVIEW

**Comment by macnibblet** [comment]
Really looking forward to this!

**Comment by 3h4x** [comment]
Tests are failing on s3 bucket that already exist but I verified that it doesn't so I'm going to trigger tests once again

**Comment by maximmi** [comment]
@helvalius @macnibblet here is new release: https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment/releases/tag/0.21.0

**Comment by macnibblet** [comment]
We are still having problems with unrelated changes

```
      - setting {
          - name      = "SpotFleetOnDemandAboveBasePercentage" -> null
          - namespace = "aws:ec2:instances" -> null
          - value     = "70" -> null
        }
      + setting {
          + name      = "SpotFleetOnDemandAboveBasePercentage"
          + namespace = "aws:ec2:instances"
          + value     = "70"
        }
      - setting {
          - name      = "SpotFleetOnDemandBase" -> null
          - namespace = "aws:ec2:instances" -> null
          - value     = "0" -> null
        }
      + setting {
          + name      = "SpotFleetOnDemandBase"
          + namespace = "aws:ec2:instances"
          + value     = "0"
        }
      - setting {
          - name      = "SpotMaxPrice" -> null
          - namespace = "aws:ec2:instances" -> null
        }
      + setting {
          + name      = "SpotMaxPrice"
          + namespace = "aws:ec2:instances"
          + value     = "null"
        }
```

**Comment by helvalius** [comment]
@macnibblet  I created a new pull request #125 . The issues that you have were added in between merging my pull request with missing the resources fix in #115 .
@maximmi  could you check the new pull request and merge if everything is fine? :) thx

**Pull request merged**
