### PR TITLE
Add a variable for Availability Zones

### PR DESCRIPTION
**Pull request by guikcd**
## what

Change the default Availability Zones from `Any 2` to  `Any`.

## why

If there is more than 2 AZs in a region, use all AZs:

`Availability Zones (AZs) are distinct locations within a region that are engineered to be isolated from failures in other AZs and provide inexpensive, low-latency network connectivity to other AZs in the same region. Choose the number of AZs for your instances.`

For example region **eu-west-1** and **eu-west-3** has 3 differents AZs.
~~I think there is no need to provide a variable for this; it works on all cases (1 instance, 3 instances, 6 instances, etc...).~~

## reference

* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
* https://github.com/jsonmaur/aws-regions (unofficial list of all AZs per regions)

### CODE REVIEW

**Comment by guikcd** [comment]
FYI, Travis-ci has some isues with public builds: https://www.traviscistatus.com/incidents/69gf0dn51g0v

**Comment by osterman** [comment]
There are practical implications of switching to `Any`. Your argument though is strong, but I would prefer making it a variable since the answer is "it depends" and prefer not to be that opinionated on this point.

My "weak" counter-arguments:
- Interzone data transfers are billed extra. If you're running in more zones and doing intercommunication between instances, then costs will be higher
- If one zone has fewer instances than the other, it can get overloaded due to the semantics of how ELBs distribute traffic. Having fewer zones reduces the likelihood of that happening.

**Comment by guikcd** [comment]
It's ok, i'll create a variable for this to override the sane default.

**Comment by guikcd** [comment]
Done

**Pull request merged**
