### PR TITLE
Add Support for Application Version Label

### PR DESCRIPTION
**Pull request by velmoga**
Hello, gents. 
I've taken your module for one of my projects, it made him work perfectly. Create all needed resources. But it didn't deploy any code to created environment. I bring small fix that helps me to deploy code.

### CODE REVIEW

**Comment by velmoga** [comment]
I'm ready to make any code style changes. Today it's the first day with terraform for me and your modules help me for a rapid start.

**Comment by osterman** [comment]
Thanks @velmoga ! I'll have @aknysh take a look. Also, have a look at this repo for an advanced reference architecture using CodeBuild/CodePipeline for CI/CD: 

https://github.com/cloudposse/terraform-aws-jenkins

**Comment by velmoga** [comment]
@osterman thanks for fast reply. I've fixed code format. Waiting for review.

**Comment by aknysh** [comment]
@velmoga 
thank you for testing and submitting the PR.
just a few questions to confirm (since you are testing it now, and the doc does not say anything specific https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_environment.html#version_label):

1. Do you need to always provide a value for `var.version_label` or it could be empty?
2. If left empty, will it deploy the latest version?

thanks

**Comment by velmoga** [comment]
1. `var.version_label` can be an empty string. It defined as default value.  
2. In this case elastic beanstalk deploy clean environment with demo page. 

```Congratulations!
Your AWS Elastic Beanstalk PHP application is now running on your own dedicated environment in the AWS Cloud

You are running PHP version 7.1.13```

Something like this.

**Comment by velmoga** [comment]
Also I use your rds module to deploy database and they can't work together with beanstalk module. 

https://github.com/velmoga/terraform-aws-rds/commit/597510d74eac4afbe2f511e3c1cb03de8bf592c0

They have same security group name. I made fix, but it doesn't looks great to contribute it.

**Pull request merged**
